version: "3.9"

services:
  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - ./../:/var/www/
    networks:
      - appnetwork
    working_dir: /var/www/

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm
    networks:
      - appnetwork

  db:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: unless-stopped
    logging:
      driver: none
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ../docker/mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    networks:
      - appnetwork

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: ${COMPOSE_PROJECT_NAME}-pma
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: unless-stopped
      ports:
        - ${PMA_PORT}:80
      networks:
        - appnetwork

volumes:
  mysql-data:

networks:
  appnetwork:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge